parser: babel-eslint

env:
  es6: true
  jest: true

extends:
  - airbnb
  - airbnb/hooks
  - prettier
  - prettier/react
  - plugin:prettier/recommended
  - plugin:flowtype/recommended

plugins:
  - prettier
  - flowtype
